version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    network_mode: bridge
    command: sleep infinity
    depends_on:
      - redis
      - postgres

  redis:
    image: redis
    user: "redis:redis"

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: outline
    user: "postgres:postgres"

volumes:
  postgres-data:
